# -*- coding: utf-8 -*-
"""Sentiment Analysis on Product Reviews

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfcup_LtES1dlSwMGm9xhuNO5hYSr4jJ

## Amazon Fine Food Reviews
This dataset consists of reviews of fine foods from amazon. The data span a period of more than 10 years, including all ~500,000 reviews up to October 2012. Reviews include product and user information, ratings, and a plain text review. It also includes reviews from all other Amazon categories.
### Dataset :- https://www.kaggle.com/datasets/snap/amazon-fine-food-reviews
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Reviews.csv")
df

display(df.head(10))

"""# Task 2 - Data Cleaning

### Removing rows with empty or null review text
First, I will remove rows where the 'Text' column is empty or contains null values. Although the previous `isnull().sum()` showed 0 nulls for 'Text', it's good practice to ensure no empty strings are present either.
"""

df.isnull().sum()

initial_rows = df.shape[0]
df = df[df['Text'].astype(bool)]
df = df.dropna(subset=['Text'])
rows_after_null_empty = df.shape[0]
print(f"Removed {initial_rows - rows_after_null_empty} rows with empty or null review text.")
display(df.head())

"""### Removing duplicate reviews
Next, I will identify and remove duplicate review entries. Duplicate reviews can skew analysis, so it's important to ensure each review is unique.
"""

initial_rows = df.shape[0]
df.drop_duplicates(subset=['Text', 'Score', 'Summary'], inplace=True)
rows_after_duplicates = df.shape[0]
print(f"Removed {initial_rows - rows_after_duplicates} duplicate review entries.")
display(df.head())

"""### Keeping only relevant columns
Finally, I will keep only the 'Text' and 'Score' columns, as requested, to simplify the DataFrame for further analysis.
"""

df = df[['Text', 'Score']]
display(df.head())

"""# Task 3 - Sentiment Analysis"""

!pip install textblob

"""### Sentiment Analysis using TextBlob
I will use `TextBlob` to calculate the sentiment polarity score for each review. The polarity score ranges from -1 (negative) to 1 (positive).
"""

from textblob import TextBlob

# Function to get polarity score
def get_polarity(text):
    return TextBlob(text).sentiment.polarity

# Apply the function to the 'Text' column to get polarity scores
df['Polarity'] = df['Text'].apply(get_polarity)
display(df.head())

"""### Labeling Reviews based on Polarity Score
Now, I will categorize each review based on its polarity score:
- Positive: polarity > 0
- Negative: polarity < 0
- Neutral: polarity = 0
"""

def get_sentiment(polarity):
    if polarity > 0:
        return 'Positive'
    elif polarity < 0:
        return 'Negative'
    else:
        return 'Neutral'

# Apply the function to the 'Polarity' column to get sentiment labels
df['Sentiment'] = df['Polarity'].apply(get_sentiment)
display(df.head())

"""### Sentiment Distribution

"""

sentiment_counts = df['Sentiment'].value_counts()
print(sentiment_counts)

"""# Task 4 - Visualization (Minimum 3 charts)

### Sentiment Distribution Visualization
Let's visualize the distribution of Positive, Negative, and Neutral sentiments using different chart types.

### Chart 1: Bar chart showing count of Positive, Negative, and Neutral reviews
"""

# Chart 1: Bar chart showing count of Positive, Negative, and Neutral reviews
plt.figure(figsize=(8, 6))
sns.barplot(x=sentiment_counts.index, y=sentiment_counts.values, palette='viridis')
plt.title('Count of Reviews by Sentiment')
plt.xlabel('Sentiment')
plt.ylabel('Number of Reviews')
plt.show()

"""### Chart 2: Pie chart showing the percentage distribution of sentiments"""

# Chart 2: Pie chart showing the percentage distribution of sentiments
plt.figure(figsize=(8, 8))
plt.pie(sentiment_counts.values, labels=sentiment_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('viridis'))
plt.title('Percentage Distribution of Sentiments')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""### Chart 3: Original Rating vs. TextBlob Sentiment Polarity
Let's explore the relationship between the user's explicit star rating (Score) and the calculated TextBlob sentiment polarity. This can help us understand how well TextBlob's sentiment aligns with the numerical ratings.
"""

# Group by original Score and calculate the mean polarity for each score
score_sentiment_mean = df.groupby('Score')['Polarity'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='Score', y='Polarity', data=score_sentiment_mean, palette='coolwarm')
plt.title('Average TextBlob Polarity by Original Review Score')
plt.xlabel('Original Review Score (1-5)')
plt.ylabel('Average Sentiment Polarity')
plt.ylim(-0.5, 0.8) # Set appropriate y-limits for polarity range
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""## Task 5 - Insights & Summary

Our analysis reveals a highly positive sentiment among customers, with approximately **88.4% of reviews being positive**. While a small portion (around 10.1%) are negative, customers mostly complain about issues leading to low star ratings, which significantly correlate with low TextBlob sentiment polarity. What was surprising is the strong linear correlation between the original star ratings and the TextBlob polarity, confirming TextBlob's effectiveness in this dataset, and the relatively small number of neutral reviews. A key recommendation for the business is to actively analyze the specific content of negative reviews (especially those with 1 or 2 stars) to identify recurring issues and areas for product or service improvement, as this dataset clearly segments sentiment.
"""